### ISSUE TITLE
New quest Unknown Recipient problems (Win)

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1452] opened 2022-04-11 00:30 UTC
For starters, the Hub interactions are the same as before, as in, the intercom barely acknowledges you at first and doesn't seem to interact with the quest at all. Also, at least at first, as usual, it is the only NPC in the area.

Second, the item is broken. It has no weight, no description, no category, it is bugged on display, it causes an error message on load up, and can't be sold or used in any way to finish the quest. At least it does have the sprite of the supposed hdd it is.

The quest is nice though, as it can help you find a Hub after you find a Refugee Center (which is much easier to track, due to the shelters), which is good value for a player looking to trade. Wish it wasn't broken though.

**Comment by WeisserRitter** [comment] 2022-05-09 23:33
This happened to me recently too. Here is a more in-depth look into the reason behind the bug and how to trigger it.

Upon accepting the quest to deliver a HDD with some data from FEMA from the refugee center to the HUB, the game throws an error displaying that the quest item (fema_data) cannot be found. The FEMA data quest item is not defined in the code, and neither is the questline attached to it on the Hub intercom's side. Perhaps it was copied content from CDDA that wasn't properly pruned. 

# Steps To Reproduce

1. Go to refugee center
2. Talk to the merchant at the entrance behind the window, choosing the option where you ask if he has heard any news from outside. 3. You can then ask him a question something like "m. Any other settlements nearby?"
4. After he replies, choose the second option, "b. Just that?" and it will continue into a job offer after some dialogue.
5. Accept the job, and the game will throw the error.

# Expected behavior

Either the quest should not be possible to access at all, or it should be added back in. It seems to be an independent sidequest for connecting the hub and the refugee center though, 

# Screenshots

![error](https://user-images.githubusercontent.com/27070193/167513506-2a61c5ba-c814-4722-83b3-a2015ccb8d98.png)
![error2](https://user-images.githubusercontent.com/27070193/167514032-01aa6260-43e6-47b1-80c4-46a8e9871034.png)



# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 41ae57c [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Battle Maid Redux [battle_maid],
    C.R.I.T Expansion Mod [crt_expansion],
    No Hope [no_hope],
    Elevated bridges [elevated_bridges],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Craftable Gun Pack [craftgp],
    Advanced Technologies [advtech],
    Advanced Gear [adv_gear],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Bootleg Walkers [Bootleg_Walkers],
    Makeshift Items Mod* [makeshift__],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Pneumatic fun [pneumo_fun],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Blazemod - Vehicle Additions Pack* [blazemod__],
    No Rail Stations [No_Rail_Stations],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Disable NPC Needs [no_npc_food],
    Fuji's Military Profession Pack [fuji_mpp],
    Prevent Zombie Revivication [no_reviving_zombies],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Super Job [SuperJob],
    No Bionic Slots [no_cbm_slots],
    Nonperishable Overhaul [Nonperishable_Overhaul]
]

**Comment by Rogue85** [comment] 2022-07-01 19:33
I confirm that there is a problem in the latest version

**Comment by olanti-p** [comment] 2023-09-23 00:27
Should be fixed by #2443 + #3066

**Closed by olanti-p** 2023-09-23 00:27 UTC
Labels: bug
