### ISSUE TITLE
Abherant behavior in crafting Makeshift Hammer

### ISSUE THREAD

**Issue by narkiel** [cataclysmbnteam/Cataclysm-BN#3857] opened 2023-12-09 18:11 UTC
### Describe the bug

When attempting to create a Makeshift Hammer, despite having all the required skills and materials, I receive the message "You can't do that!" Possibly relevant is that the "chunk of steel" component shows as brown (dirty?) in the recipe

### Steps To Reproduce

1. Load the attached saved game
2. Attempt to craft a Makeshift Hammer

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 2e57319 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

[Lyerly.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13625271/Lyerly.zip)

**Comment by 6DollarSuit** [comment] 2023-12-10 14:44
Looking at the save, it's because you're trying to use one chunk of steel as both a tool (hammering 1) and component of the craft. You're trying to hit the steel with _itself_. Working as intended, but the UI could be a bit more clear about it.

**Comment by narkiel** [comment] 2023-12-10 15:26
Ahh ok, that makes perfect sense then. Thanks for clarifying.

**Comment by scarf005** [comment] 2023-12-10 22:31
yeah, the UI could see some improvement. for now, i'll close the issue as intended. thanks for the report nonetheless.

**Closed** 2023-12-11 01:02 UTC
Labels: bug
