### ISSUE TITLE
Zones Manner Error: "Farm Plot" with no seed makes crash

### ISSUE THREAD

**Issue by Restar-JS** [cataclysmbnteam/Cataclysm-BN#4043] opened 2024-01-01 11:39 UTC
### Describe the bug

"Fam plot" action with "No seed" makes game crash.

Save attached

### Steps To Reproduce

1. Press "Y" to set "Farm: plot"
2. Pick "No seed" option
3. Set area which has dirt mound
4. Press "O" and do fram plots
5. Game shows error messages and crashes

### Screenshots

<img width="960" alt="스크린샷 2024-01-01 203120" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/150272259/66c3543e-f6da-4a6a-aeb8-af40a2fe9072">
<img width="444" alt="스크린샷 2024-01-01 203031" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/150272259/41067ed9-47dc-4a1c-8d66-a0680f36783e">
<img width="275" alt="스크린샷 2024-01-01 203039" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/150272259/ba41f50f-168f-49f5-bdfb-fe40c83d6d90">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2861 (23H2)
- Game Version: 0.5 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

[Test.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13804352/Test.zip)

**Comment by ekaratzas** [comment] 2024-03-04 03:51
looks like a duplicate of https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4243 which has already been fixed

@scarf005 should we close this?

**Comment by scarf005** [comment] 2024-03-04 03:52
fixed by #4262

**Closed** 2024-03-04 03:52 UTC
Labels: bug

**Comment by Restar-JS** [comment] 2024-03-04 16:11
Yeap

2024년 3월 4일 (월) 오후 12:52, scarf ***@***.***>님이 작성:
