### ISSUE TITLE
"Prevent Zombie Revivification" mod does not take into account ferals.

### ISSUE THREAD

**Issue by RobbieNeko** [cataclysmbnteam/Cataclysm-BN#4412] opened 2024-03-30 23:17 UTC
### Describe the bug

Ferals still must be pulped in order to prevent revivification, when the mod should disable it.

### Steps To Reproduce

1. Kill a feral with the mod on.
2. Look at the little graphic displaying that the corpse is unsafe and will revive.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/30732426/3a143dd1-9afb-4984-8f8d-a0f95c699101)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 2a9f8cd [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Magical Nights [MagicalNights],
    Stats Through Kills [stats_through_kills],
    Faster Stamina Regen [stamina_regen_buff],
    Stronger archery [bow_opness]
]

**Comment by Ignaramico** [comment] 2024-03-30 23:51
i noticed that it happens with the dinos too

**Comment by chaosvolt** [comment] 2024-03-31 18:18
Ah, the issue's root cause is, no revival is implemented this way:
```
  {
    "type": "monster_adjustment",
    "species": "ZOMBIE",
    "flag": { "name": "REVIVES", "value": false }
  },
```
So we'd need to either:
1. Figure out how to support monster adjustments being able to mess with the `zombify_into` property.
2. Or convert it into an external option and hardcode checks for that option into all relevant functions.

**Comment by Ignaramico** [comment] 2024-03-31 21:21
always thought the mob had to have the flag for the zombify to work

**Comment by Lamandus** [comment] 2024-04-05 11:06
I mean to be fair, it does what it does correctly, prevent zombies to revive. Ferals (and Dinos) aren't zombies, yet.

**Comment by RoyalFox2140** [comment] 2024-08-10 18:26
@chaosvolt Fixed when you merged https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4708

**Comment by chaosvolt** [comment] 2024-08-10 18:52
![image](https://github.com/user-attachments/assets/549f9cdf-89ce-40cd-86da-0477cf3c6109)

**Closed by chaosvolt** 2024-08-10 18:52 UTC
Labels: bug
