### ISSUE TITLE
Cutting rubber boots gives too much chunk of rubber

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3547] opened 2023-11-04 12:23 UTC
### Describe the bug

I was looking for chunks of rubber and cut some rubber boots only to get 600+ ruber.

Cutting up tyres doesn't even give anything near this amount.

### Steps To Reproduce

1. find rubber boots
2. cut rubber boots
3. get 600+ rubber chunks
4. Wonder what kind of dimensional rubber boots they were...
5. ???
6. Profit

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/1fb7b0e1-c2f9-4ee7-bd53-37b5bf78cd8d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: daddaec [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    Project: Pack Rat [Jake's_Squirrel_mod],
    Add Bandits Extended+ [GOV_BANDITS_KAI_R],
    NPC Increased Location Spawns Combined [npc_increased_location_comb],
]

**Comment by AlecWhite** [comment] 2023-11-20 13:17
I don't know if it is my version but I don't get the same bug. 
I'm getting either 25-24 rubber chunks with a 10 skill survivor, or with a latest selfcompiled version 14 rubber chunks with a 0 skill survivor
![rubber boots](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/16262515/d590b98a-7781-454a-aaed-8d59a11577a9)

**Comment by Unrepentant-Atheist** [comment] 2023-11-25 09:36
Nope, not mod related. I get 625 in the latest experimental with only bn too. I have no idea what you're doing, but it's still bugged. However, pay attention to what the log says and what's acutally on the floor. It says "salvaged 25 chunk" for me in the window, but there's actually 625 chunks on the floor:

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/7a48f3e8-844e-43fb-9dd7-7250425afdc9)

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 428d071 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn]
]

**Comment by scarf005** [comment] 2023-11-25 09:41
caused by cutting items with charges giving `cut yields` * `charges`, not `cut yields`.
will be fixed by #3489: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3489/commits/360d8bdcca884373206f98bb26e20d674cbd1d15

**Closed** 2023-12-25 03:53 UTC
Labels: bug, confirmed
