### ISSUE TITLE
Crashes when installing bionics due to afteshock mod

### ISSUE THREAD

**Issue by asterix-a** [cataclysmbnteam/Cataclysm-BN#178] opened 2020-11-02 13:40 UTC
# Describe the bug

Game Crashes if you choose instal bionic in autodoc

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 2bd90b4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

Further, there is too much text, I will not understand what the error is, but I found a solution

# Steps To Reproduce

Just tray instal any cbm on autodoc and you game crashes

SOLUTION THIS PROBLEM: 
JUST DELETE "OPTION.JSON" FILE AND GET OVER THE CRASHES

**Comment by Coolthulhu** [comment] 2020-11-02 15:08
Aftershock enabled? If so, most likely dupe of #165

**Comment by Coolthulhu** [comment] 2020-11-02 16:06
I assume a dupe of that Aftershock requirements thing. If it still happens, I'll reopen.

**Closed by Coolthulhu** 2020-11-02 16:06 UTC
