### ISSUE TITLE
Running any world without Item Category Overhaul mod causes EVERY activity to break on that world permanently

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#5262] opened 2024-08-28 00:16 UTC
### Describe the bug

If you decide not to enable Item Category overhaul on my game version, you simply can no longer use activities. You get these errors for every type in the game. 

DEBUG    : The do_turn function ACT_ARMOR_LAYERS doesn't correspond to a valid activity_type.

 FUNCTION : static void activity_type::check_consistency()
 FILE     : src/activity_type.cpp
 LINE     : 91
 VERSION  : BN 8db8a67
DEBUG    : The do_turn function ACT_ATM doesn't correspond to a valid activity_type.

 FUNCTION : static void activity_type::check_consistency()
 FILE     : src/activity_type.cpp
 LINE     : 91
 VERSION  : BN 8db8a67

### Steps To Reproduce

1. Download latest, or my version.
2. Make a world without Item Category Overhaul.
3. Save and reload the world once.

### Screenshots

![image](https://github.com/user-attachments/assets/3dbb7d7b-ec86-44da-a477-59da9d2294be)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Bazzite; Description: Bazzite 40 (FROM Fedora Kinoite); Release: 40; Codename: Holographic; 
- Game Version: 8db8a67 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water],
    No Filthy Clothing [no_filthy_clothing],
    No Wasps [No_Wasps],
    Item Category Overhaul [Item_Category_Overhaul]
]

**Comment by KheirFerrum** [comment] 2024-08-28 00:32
Cannot reproduce. Tried with world spawned without mod, world spawned with mod, and edited world mod midsave.

**Comment by RobbieNeko** [comment] 2024-08-28 00:37
Also cannot reproduce by creating a world without the mod, saving and re-entering the world, or closing and reopening the game. Also tried adding mod mid-save, still didn't cause anything to happen.

**Comment by RoyalFox2140** [comment] 2024-08-28 00:37
Can't figure it out. Possibly a problem with my system. It triggers inconsistently when I load the world.

**Closed** 2024-08-28 00:38 UTC
Labels: bug, needs verification, src, game-breaking
