### ISSUE TITLE
Crafting recipe search full description problem

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#2903] opened 2023-05-28 21:26 UTC
### Describe the bug

When searching for crafting recipes inside of crafting UI, there is a possibility to search for 'full description of resulting item' which will show any recipes that have a text inside of a recipe.
I used to be able to search for unarmed weapons or items that fit abnormally large mutated anatomy but this isn't possible anymore.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/72284934/b81f1dbd-a997-4634-9746-d748ba8a6e13)
This doesn't show any result while i have the item available for crafting:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/72284934/3a1d034a-9530-4e9a-8fda-234607f8348a)
Tried different searches and my conclusion is that it ignores all the lines that are starting with * in front of it.:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/72284934/2ad8b69a-9ea5-41cb-bddd-975b4a78d857)

### Steps To Reproduce

1. Open crafting menu and find an item that supports unarmed fighting styles or reach attacks.
2.  Make a search for d:unarmed fighting styles or d:reach attacks
3. Observe that you get no result.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 5b815d9 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Prevent Zombie Revivication [no_reviving_zombies],
    XL clothing [XL_clothing],
    no ups mp3 [no_UPS_mp3]
]

**Comment by olanti-p** [comment] 2023-09-23 01:21
Possible dupe of #2455

**Closed** 2023-10-16 23:54 UTC
Labels: bug
