### ISSUE TITLE
Can't load save with latest build

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3485] opened 2023-10-23 06:20 UTC
### Describe the bug

Can't load the save with the latest build [Cataclysm-BN experimental build 2023-10-23-0319](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-10-23-0319) due to

```
08:14:55.559 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp:1020 [load_character_tab] Error: item group "games" already defined with type "distribution"
```
Can start a new game tho.

### Steps To Reproduce

1. Start a new game
2. Try
3. Fail
4. ???
5. Don't profit

### Versions and configuration

There's no log, since there's no game.

**Comment by scarf005** [comment] 2023-10-23 06:22
cc @Zlorthishen could you have a look at this?

**Comment by Unrepentant-Atheist** [comment] 2023-10-23 06:32
Well, since I can start a new game, I guess it's not really an issue?

**Comment by chaosvolt** [comment] 2023-10-23 15:22
One of the mods your old save used most likely adds an item to the `games` itemgroup, which presumably errors since the mod expects it to be a collection but Zlor added it as a distribution. Your lack of an error on a new game means you likely didn't include the mod that caused this in your new world's modlist.

Will likely have to notify @Kenan2000 since they he need to check the modpack for mods that inject into that itemgroup, and whoever else might be maintaining mods that could've done so?

**Comment by Unrepentant-Atheist** [comment] 2023-10-23 19:58
>Your lack of an error on a new game means you likely didn't include the mod that caused this in your new world's modlist.

Can't be, since I started a new game in exactly the same world (world is set to reset on death). Here I just manually reset the world and started a new game. Didn't change the mod list at allt.

**Comment by scarf005** [comment] 2023-11-25 09:51
Closing as the issue is not reproducible. Please reopen if the issue happens again.

**Closed by scarf005** 2023-11-25 09:51 UTC
Labels: bug
