### ISSUE TITLE
Add martial art style to Crafting UI category search

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3410] opened 2023-10-10 19:03 UTC
### Is your feature request related to a problem? Please describe.

I'd like to be able to list craftable weapons by defining or searching for martial art style I currently know. Searching `d:krav maga` produces no results even though I know the martial art style.

### Describe the solution you'd like

1. Open craft UI
2. Select search/filter
3. Add martial art style
4. Produce craftable results

**Comment by olanti-p** [comment] 2023-10-16 21:47
Duplicate of #2903.
Item description states what martial arts you can use it with, it's just `d:` search is overall broken at the moment.

**Closed by olanti-p** 2023-10-16 21:47 UTC
Labels: enhancement
