### ISSUE TITLE
crash upon grenades/40mm exploding [0.2 STABLE]

### ISSUE THREAD

**Issue by boomerman22** [cataclysmbnteam/Cataclysm-BN#2706] opened 2023-04-25 19:50 UTC
### Describe the bug

I think it started with me raiding a mall, and the game refusing to load some assets. When I throw a normal frag grenade, or shoot 40mm grenades, the game promptly seizes up, then crashes.

### Steps To Reproduce

1. Find an area with assets that the game refuses to load, preferably a mall in a city.
2. get away from that area and wait for some time
3. Attempt to use frag or 40mm grenades

### Versions and configuration

OS: Win 10
version: 0.2 Stable
Mods loaded: Disable NPC Needs, Simplified Nutrition, Elevated bridges, No Hope, C.R.I.T Expansion Mod

**Comment by scarf005** [comment] 2023-05-12 06:00
> assets that the game refuses to load

1. sorry, but could you explain this in detail? it's not clear what does `assets that the game refuses to load` mean in this context. screenshots are welcome.
2. could you try again in experimental and check if the bug persists?

**Comment by scarf005** [comment] 2023-09-24 01:50
as we were unable to reproduce the issue and no further reproduction was given, we'll close this issue for now.
please reopen the issue again if the issue persists in latest experimental.

**Closed by scarf005** 2023-09-24 01:50 UTC
Labels: bug, needs verification, crash
