### ISSUE TITLE
Can't pick up mined rocks

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#1834] opened 2022-09-06 03:11 UTC
### Describe the bug

When I mine a boulder, the rocks left over in the pit cannot all be picked up. The exact amount varies, but I generally get about 2/3rds of them, and never the sharp rocks. I have only tested with a bone pickaxe, not sure if it happens with every single pickaxe. The exact error given is:

 DEBUG    : lost target item of ACT_PICKUP

 FUNCTION : do_pickup
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\pickup.cpp
 LINE     : 423
 VERSION  : BN 9a75e5d

### Steps To Reproduce

1. Get bone pickaxe
2. Mine boulder
3. Pick up rocks from pit
4. Do not pick up all rocks

### Expected behavior

To pick up all rocks.

### Versions and configuration

OS: Windows 10

Game Version: Experimental 2022-09-03-1209

Graphics Version: Undead_People (New Version)

Ingame Language: English

Mods Loaded: Disable NPC Needs, Simplified Nutrition, Elevated Bridges, Aftershock, Bio-Synth Robot, C.R.I.T. Expansion, UnderrailMetro Mod, Abrahms Recipes 1, Advanced Technologies, Alexs Mutant Power Armor, anti-fungal gear, Armor Up! Survivor Expansion, Arsenal Breach, Artyoms' Gun Emporium - Reloaded, Bens' GF recipes, BioCo Content, Bionic Space Expander, Bionics Systems Recipes, Modular Turrets with No Blacklist, Bootleg Walkers, CBM Equipment, CIVILIAN POWER ARMOR, Craftable Ammo and Mags, Craftable Gun Pack, Culinary Days Ahead, Dried Fruits, Expanded Archery, Garden Pots*, Gourmand's Graces, Homemade Fungicide, Icecoon's Arsenal, Large Capacity Storage CBMs, Make a Lot of Items, Makeshift Items*, Metal Materials, MOD to grow tea leaves, More Armors, More Makeshift Stuff, More Survivor Notes, Nimian Manufacture Guns, Pipe Revolver Rifles, Pixel's Various Fuckery, Project APEX, Ricky's Future Armory, Rivtech Beam Swords, Survivor's Lost item, Survivor's crowbar, The Glory of Cereal!, The Vermillion Mod, Thermal Electric UPS, Wild Living, XEAS, Draco's Dog Mod, Draco's Pig Mod, Salvaged Robots*, Alternative Map Key, CDDA Variety Pack, Compatible Ninja MOD, Even More Mutations, Hydroponics*, Jury-Rigged Robots, Merchant Mod, Mining Mod, More Survivor Stuff, Mug NPCs, NPC Recruitment Options, Sarcophagi Access, THRESHOLD, Wandering Masters, Whaleys Hair Mod, Alternative Basement Layouts, Caches, No Rail Stations, Ships from Oa Additional Buildings, Trailer Parks, Water Towers, Whaleys TALL Buildings, Pneumatic fun, Blazemod - Vehicle Additions Pack, Folding Parts Pack*, Shrub it off, Amplified @'s Features, Graphical Overmap, Hair and Skin Color Cosmetics UDP and MXotto+ version, Zetsukaze's Hair - 0.E EDIT, PKs Rebalancing, Zet's Hair - PKs Rebalancing, Bug's Life, DinoMod, Autodoc Harmless and Perfect, Fuji's Military Profession Pack, Gunslinger Mod, Manual Bionic Installation, Mutation Changes Snofielf, Necropolis Actually Findable, No Lifting Reqs, Prevent Zombie Revivication, SpeedyDex, Stats Through Skills, Stronger archery, Tame Bugs, Targeted Mutations, ZSFIXED_C:DDA Extra Professions and Gears, No Filthy Clothing, Compatible Add Bandits, Mutant Animals, Mutant Insects

### Additional context

[Turner.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/9492985/Turner.zip)

**Comment by yay855** [comment] 2022-09-06 11:32
It fixed itself when I saved and reloaded. I feel like an idiot for not trying that first.

**Comment by Coolthulhu** [comment] 2022-09-20 16:40
Can't reproduce. I'll close it for now. If it appears again, we can reopen.

**Closed by Coolthulhu** 2022-09-20 16:40 UTC
