### ISSUE TITLE
Body temerature being too low again

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#1350] opened 2022-02-19 17:06 UTC
# Describe the bug

> Chasovolt
> why are my hands still chilly on autumn 14, standing right next to a fire, indoors, while wearing 65 warmth worth of glove. >:C 
![изображение](https://user-images.githubusercontent.com/17512620/154810997-fcadeb1a-3a57-4c5e-9d9e-315cad4a852c.png)

> I'm not sure if it's temperature or warmth processing that's acting up for this, but since I'm 5 points shy of winter gloves and 20 F is usually considered cold but tolerable for a lot of places as long as there's no wind (which there shouldn't be since I'm currently indoors)...
![изображение](https://user-images.githubusercontent.com/17512620/154811016-1dd2629c-19e5-44bd-9d41-5e6ec8807d62.png)

# Steps To Reproduce
1. Check body temperature at cold seasons (closer to winter)

# Expected behavior
Clothes should provide needed protection

Probably related:
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/397
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/383

**Comment by chaosvolt** [comment] 2022-02-19 17:13
Tested a fresh world starting on winter day 1, spawned in the above setup of 65 warmth, and got expected result:
![image](https://user-images.githubusercontent.com/11582235/154811289-05f8126e-789b-4311-bc39-7095e4005152.png)

Thermometer showed it to be 21 F, was indoors. Testing fur gloves (70 warmth) instead had the hand temps go from -30 to +15 (!):
![image](https://user-images.githubusercontent.com/11582235/154811372-a3508907-8435-49ac-9acb-32f1c95c5616.png)

**Comment by chaosvolt** [comment] 2022-02-19 17:18
And here's the save for the scenario shown in the OP, from the succession game where I encountered this. Load in the character `Texas Red`, currently the nearby oven is unlit so every body part will be chilly, hands still have the above clothing combo:

https://drive.google.com/file/d/1kcx8MJrqJw2cIXP7AFWE1yKC4ga5Pk88/view?usp=sharing

Zip was too big to upload due to it being a save with 4 different characters active due to it being passed around between multiple players.

**Comment by chaosvolt** [comment] 2022-02-19 18:50
Okay, weird finding: I'm comfortable outside with the same setup that would be uncomfortable indoors, thermometer shows same temperature regardless. 17 F is fine when outdoors even if my hand clothing warmth is only 35, but step inside and I'm at:
![image](https://user-images.githubusercontent.com/11582235/154814769-16c8c09b-b020-4762-a4b7-60478ee7f72b.png)

**Comment by Coolthulhu** [comment] 2022-02-22 10:56
> I'm comfortable outside with the same setup that would be uncomfortable indoors, thermometer shows same temperature regardless. 

I suspect sunlight effect. Will check forced weather.

**Comment by Coolthulhu** [comment] 2022-04-03 12:29
Probably caused by the warmth stacking problem. I'm assuming it's fixed now. If not, I'll reopen.

**Closed by Coolthulhu** 2022-04-03 12:29 UTC

**Comment by chaosvolt** [comment] 2022-04-03 15:50
Nice. Since I ran into this while stacking lower-warmth items to reach a value high-warmth items normally grant, that sounds like the probable cause.
