### ISSUE TITLE
Things disappear from merchants

### ISSUE THREAD

**Issue by Anthraxmkv** [cataclysmbnteam/Cataclysm-BN#3586] opened 2023-11-07 02:56 UTC
### Describe the bug

When approaching any trader, items within his "trading radius", thats meant to be on sale, just disappear.

### Steps To Reproduce

1. Find any trader with items around him.
2. Open trading menu thru dialog.
3. His goods are the only things in his inventory, items on the map disappear.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/85070034/c9bb3704-7239-4c5c-accf-a2288f0183ab)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/85070034/64677dd2-5d59-47f9-8b00-e5daaa0548b0)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/85070034/5770c4b4-36f8-4c30-84be-2151f282810f)

### Versions and configuration

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13275088/debug.log)

### Additional context

[Бринсон_hell_copy.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13275121/_hell_copy.zip)

**Comment by scarf005** [comment] 2023-11-07 02:58
probably duplicate of #3476.

**Closed** 2023-11-07 03:48 UTC
Labels: bug
