### ISSUE TITLE
Charcoal Forges and Charcoal smoker don't use any charges anymore

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#4996] opened 2024-07-16 06:56 UTC
### Describe the bug

the amount of charcoal in a charcoal smoker/forge stays the same.

### Steps To Reproduce

1. Have a loaded charcoal forge
2. create anything that uses a lot of charcoal (for example lump of steel from scrap)
3. Ignore the "you don't have enough charges" message
4. craft away. Even without the message the amount of charcoal stays the same.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3880 (23H2)
- Game Version: ebb8844765 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies],
    Lootzones [Lootzone],
    No Filthy Clothing [no_filthy_clothing],
    Limit Fungal Growth [limit_fungal_growth],
    MSX Fake Snow [UDP_BN_FAKE_SNOW],
    No Lifting Reqs [disable_lifting],
    Prevent Zombification [no_zombify]
]

### Additional context

[Ortenaukreis.zip](https://github.com/user-attachments/files/16244237/Ortenaukreis.zip)

**Comment by RoyalFox2140** [comment] 2024-08-14 01:57
Duplicate of https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3754

**Closed by RoyalFox2140** 2024-08-14 01:57 UTC
Labels: bug, confirmed, src
