### ISSUE TITLE
Game hangs with build 2023-11-04-0144

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3541] opened 2023-11-04 04:11 UTC
### Describe the bug

Game seems to randomly just stop working and hangs about for infinite time.

1st time I just left a city and came upon a horde killing each other with Really Dark Sky mobs.
2nd time same thing.
3rd time I entered a grocery store and wanted to pull a shopping cart.
4th time this here.

### Steps To Reproduce

1. Just play the new build
2. Something unspecific happens (in here I crashed with my vehicle somehow)
3. Game stops
4. ???
5. Don't profit

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/ea61428e-148d-4698-87c5-2bcaf135dbc1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 7ed3776 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    Project: Pack Rat [Jake's_Squirrel_mod],
    Add Bandits Extended+ [GOV_BANDITS_KAI_R],
    NPC Increased Location Spawns Combined [npc_increased_location_comb],
    More Bandits, Testing version [More_Bandits],
    More Dangerous Encounters [More_Dangerous_Encounters],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Urban Development [Urban_Development],
    Morlock Village [morlock_village],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Really Dark Skies plus Arcana [realdarkskies_Arcana_patchmod],
    Really Dark Skies plus Cataclysm++ [realdarkskies_CATA_patchmod],
    Really Dark Skies plus Aftershock [realdarkskies_aftershock_patchmod],
    Really Dark Skies plus PKs Rebalancing [realdarkskies_PK_REBALANCE_patchmod],
    Really Dark Skies plus Secronom [realdarkskies_secronom_patchmod],
    Really Dark Skies plus C.R.I.T. [realdarkskies_CRIT_patchmod],
    Really Dark Skies plus Bio-Synth Robot Expansion [realdarkskies_gekkobots_patchmod],
    Really Dark Skies plus magiclysm [realdarkskies_magiclysm_patchmod],
    Really Dark Skies plus Morlock Village [realdarkskies_morlock_village_patchmod],
    Even More Mutations [even_more_mutations],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Salvaged Robots [Salvaged_Robots],
    Bug's life [Bug's life],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    DinoMod [DinoMod],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Really Dark Skies plus DinoMod [realdarkskies_Dino_patchmod],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Wield Wild Weapons [WIELD_WILD_WEAPONS],
    Tankmod: Revived [Tankmod_Revived],
    Valik's Machine Shop 1.1 [valikengines],
    Thog's Vehicles [Thogs_Vehicles],
    Really Dark Skies plus Thog's Vehicles [realdarkskies_Thogs_Vehicles_patchmod],
    Thog's Things [Thogs_Things],
    CDDA Variety Pack [ks_variety_pack],
    Hydroponics [hydroponics],
    Wandering Masters [wandering_masters],
    Expanded Archery [ExArch],
    MST Extra [MST_Extra],
    Makeshift Items Mod [makeshift],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Caches [P_Caches],
    Dorf Life [Dorf_Life],
    Randomized Mall [randomized_mall],
    Tekitou Map Commercial Overhaul [tekitoumap],
    Beta National Guard Camp [national_guard_camp],
    Nuclear Power Plant [NPP],
    Mug NPCs [mug_NPCs],
    NPC Recruitment Options [recruitment_options],
    Necropolis Actually Findable [necro_find],
    Lones Atomic additions [lones atomic additions],
    Lones CBM slot balance [lones_CBM_slot balance],
    Lones Flesh Raptor [flesh raptors],
    Lones Translocator Gates [translocator_gates],
    Lones Tweaks [lonestweaks],
    Chorus's Arcana Addon [Chorus Arcana Addon],
    Chorus's Gear [Chorus_Weapons],
    Chorus's CBMs [Chorus CBMs],
    Chorus's Martial Arts [Chorus_MA],
    Idzibear's Additions Testing Ground [Idzibear_Additions_test]
]

**Comment by olanti-p** [comment] 2023-11-04 17:40
Some of those may have been cases of #3552, it's common for mobs to smash vehicles into 2, and crashing a car can definitely do that.

**Comment by joveeater** [comment] 2023-11-05 13:18
I'm going to tentatively mark this as fixed by #3559. If it continues on the latest version please reopen.

**Closed by joveeater** 2023-11-05 13:18 UTC
Labels: bug, needs verification

**Comment by scarf005** [comment] 2023-11-05 13:20
marked as duplicate of #3552.
