### ISSUE TITLE
Attaching a Jumper Cable to a Jumper Cable Connector duplicates the cable

### ISSUE THREAD

**Issue by SolsticeTheTechMarine** [cataclysmbnteam/Cataclysm-BN#5391] opened 2024-09-20 14:33 UTC
### Describe the bug

Attaching a Jumper Cable to a Jumper Cable Connector duplicates the cable. this can be either from your inventory or from your hands.

### Steps To Reproduce

1: Start a new Bright Nights only world
2: Create a generator vehicle, a Jumper Cable Connector, and a large storage battery connected to the building electric grid.
3: Attach the generator to the Jumper Cable Connector.
4: After receiving cable connected message in log, observe cable still in inventory or hands.
5: Look at generator vehicle to see cable attached part.

### Screenshots

![image](https://github.com/user-attachments/assets/707fc3bf-4b50-4ca4-a6ce-e0139e8e314e)
![image](https://github.com/user-attachments/assets/7521b751-bf4d-496d-999a-9016cdf12978)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: a04dc2a [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]

**Comment by scarf005** [comment] 2024-09-21 02:16
duplicate of #5122

**Closed by scarf005** 2024-09-21 02:16 UTC
Labels: bug
