### ISSUE TITLE
Dinomod Invalid Harvest List

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#2434] opened 2023-03-16 15:04 UTC
### Describe the bug

Dinomod's harvest list for at least some of the dinosaurs are missing and/or invalid, resulting in the following errors when you kill one and a complete lack of resources when butchering.

 DEBUG    : Tried to get invalid harvest list: dino_large_leather

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\harvest.cpp
 LINE     : 27
 VERSION  : BN 4460d81

 DEBUG    : Tried to get invalid harvest list: torosaurus

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\harvest.cpp
 LINE     : 27
 VERSION  : BN 4460d81

### Steps To Reproduce

1. Spawn in/find torosaurus
2. Kill torosaurus
3. Error message
4. Butcher torosaurus
5. Nothing spawns when butchering torosaurus

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4460d81 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Aftershock [aftershock],
    DinoMod [DinoMod]
]

**Comment by Unrepentant-Atheist** [comment] 2023-04-04 22:28
Fix plx?

**Comment by olanti-p** [comment] 2023-04-13 20:04
Looks like a dupe of #2305, so should be fixed by #2369

**Closed by olanti-p** 2023-04-13 20:04 UTC
Labels: bug
