### ISSUE TITLE
Repair UI to show materials required

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#1824] opened 2022-09-01 23:49 UTC
### Is your feature request related to a problem? Please describe.

When repairing/reinforcing items/clothing you see materials required only after the act in messages.
I find this confusing and player unfriendly, especially when being low on said materials.

### Describe the solution you'd like

I'd like there being another line in the UI which would show what materials and their numbers to be be used in said repair.
![image](https://user-images.githubusercontent.com/72284934/188030897-f281c812-0c77-4ccc-a181-c9722bd537ad.png)
Something along the lines of:
Materials required: 4 leather patches or 4 kevlar plates

### Describe alternatives you've considered

none

**Comment by Drugitechnik** [comment] 2022-09-21 19:52
Duplicate of #689

**Closed** 2024-03-24 06:49 UTC
Labels: duplicate, enhancement
