### ISSUE TITLE
Food is rotting on powered vehicle Minifreezer

### ISSUE THREAD

**Issue by MgDark** [cataclysmbnteam/Cataclysm-BN#2324] opened 2023-02-05 22:07 UTC
### Describe the bug

Food placed on the cargo of a Minifreezer is not actually being protected, even when the freezer is powered on in the vehicle controls. It deteriorates even with the player staying close so i dont think is a reality bubble issue.
The item description also indicates that the food itself is not currently being protected.

### Steps To Reproduce

1. Make food, put it on the minifreezer. Use fast rotting food to see the effect
2. Wait a bit, it will show that even while on the fridge, the food is still spoiling anyways.

### Screenshots

![image](https://user-images.githubusercontent.com/16635724/216848632-76ed6e0a-dbdc-4987-8aa1-1f252efab403.png)
![image](https://user-images.githubusercontent.com/16635724/216848648-a06c25f8-775e-4c69-a1a5-1d0f1ad09e77.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 04775f5 [64-bit]
- Graphics Vers

**Comment by Ishindri** [comment] 2023-02-20 18:55
I can confirm that I'm seeing the same thing on the 0.2 stable build - freshly spawned RV with fridge and freezer enabled, and food stored in either states that it is not protected from rot.

**Comment by scarf005** [comment] 2023-04-29 02:02
Hello, could you check the latest experimental version to see if your issue has been resolved? #2653 fixed #2647, which addresses a problem similar to your problem.

**Comment by Ishindri** [comment] 2023-05-09 22:54
I've tested in the latest experimental and this appears to be fixed - items stored in active vehicle freezers/fridges now display a 'protected from rot' message when examined via the pickup menu. Waiting shows a differential in the rot rates as well. Looks like #2362 is still an issue, but through the pickup menu the information is accurate.

**Comment by scarf005** [comment] 2023-05-10 02:05
i'll close the issue as completed then. please reopen if the issue persists on newer versions.

**Closed** 2023-05-10 02:05 UTC
Labels: bug
