### ISSUE TITLE
Minireactor fuel cell dissapearance

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#100] opened 2020-10-10 12:26 UTC
# Describe the bug

After installing a minireactor with a fuel cell in the car, this fuel cell disappears after the installation is done.

# Steps To Reproduce

1. Spawn a minireactor with a fuel cell.
2. Install minireactor in a car.
3. Fuel cell is gone.

# Expected behavior

Game should either refuse to install a loaded mini reactor or unload the fuel cell before installation and leave it on the ground.
It would be even better if the cell remained in the reactor before and after the installation.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 6f00519 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Alternative Map Key [alt_map_key],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP]
]

# Additional context

**Comment by Firestorm01X2** [comment] 2020-10-10 12:36
Reference from DDA:
https://github.com/CleverRaven/Cataclysm-DDA/issues/22191

https://github.com/CleverRaven/Cataclysm-DDA/issues/22191#issuecomment-550241438
>Confirming this is still a problem in the latest experimental, this bug is now over 2 years old!

>Basically, installing a microreactor into a car ejects the plutonium cells inside. Here's the kicker: Plutonium cell charge is 1 plutonium charge per 500 power charge... Because of this I would argue that plutonium cells needed to be magazine-ized more than batteries needed to. Anyway, the logic rounds down so you can't eject fuel cells to generate free power (by rounding up) but someone forgot to check if the resulting stack has 0 charges. Someone just needs to make sure there's a greater-than-zero condition somewhere and this will be fixed.

**Comment by olanti-p** [comment] 2021-03-31 12:28
Cannot reproduce on version 15dce595572d265a33be57d0edaa04f5c016928d.
1. Debug spawned minireactor. It comes with 10'000 charge by default
2. Installed it
3. Checked in vehicle UI - reactor is empty, but there are 20 plutonium cells in player inventory (each gives 500 charge when loaded back).

Maybe it was partially used? Partially used cells vanish into the aether on unload, that could've been it.

**Closed** 2023-01-02 23:44 UTC
Labels: bug
