### ISSUE TITLE
My bike rack isn't working properly.

### ISSUE THREAD

**Issue by Unemp** [cataclysmbnteam/Cataclysm-BN#3944] opened 2023-12-19 01:24 UTC
### Describe the bug

When I attached a bike to bike racks, save the game, and load it again, I couldn't detach it.

### Steps To Reproduce

1. Attach a bike to bike racks.
2. Save the game.
3. Load the game.
4. Try to detach the bike.

### Versions and configuration

Game version 2023/12/19

**Comment by scarf005** [comment] 2023-12-19 01:28
hi, i think this issue is duplicate of #3933. it'd be grateful if we could continue the discussion there. thank you.

**Closed by scarf005** 2023-12-19 01:28 UTC
Labels: bug
