### ISSUE TITLE
Graphical overmap zoom not working

### ISSUE THREAD

**Issue by matshou** [cataclysmbnteam/Cataclysm-BN#1313] opened 2022-02-04 18:25 UTC
# Describe the bug

Zooming in and out is not possible when looking at the overmap _despite_ it being communicated to the player as possible by the keybinding menu for that screen that lists a keybinding for both zooming in and out.

# Steps To Reproduce

1. Install graphical overmap.
2. Create a new world with graphical overmap enabled.
3. Enter the world and open the overmap screen.
4. Try to zoom in and out with `z` and `Z`.

# Expected behavior

I expected to be able to use the *zoom* feature on the overmap screen.

# Screenshots

![cataclysm-tiles_sOxAx2KG1X](https://user-images.githubusercontent.com/16436920/152582216-21396d00-94bb-4229-86ef-fd852899514f.png)

# Versions and configuration

- OS: Windows 10
- Game Version: `d99ad58`
- Graphical version: Tiles
- Mods loaded: Graphical Overmap

# Additional context

This issue was also reported in https://github.com/CleverRaven/Cataclysm-DDA/issues/51564

**Comment by olanti-p** [comment] 2022-02-04 19:49
> 1. Install graphical overmap.

Only true SDL graphical overmap, the one enabled through Graphics settings tab, supports zoom. The "graphical overmap" mod is a hack that replaces overmap font with a font full of pictures, it does not support zoom similarly to how regular terrain view does not support zoom when tiles are disabled.

I guess it's a matter of disabling these keys altogether rather than keeping them as a no-op, same for zooming on terrain view without tiles. The mod imho should also be marked as legacy.

The linked issue seems to be caused by some of the true graphical overmap code that weren't added to BN (namely support for separate overmap tileset).

**Comment by matshou** [comment] 2022-02-04 20:58
> Only true SDL graphical overmap, the one enabled through Graphics settings tab, supports zoom. The "graphical overmap" mod is a hack that replaces overmap font with a font full of pictures, it does not support zoom similarly to how regular terrain view does not support zoom when tiles are disabled.

It this something we want supported though?

For me personally the look and feel of the graphical overmap that comes from the mod looks a lot better then the one provided by the game (true SDL). I have a feeling it fits better with the ASCII feeling of the game even when using tiles.

**Comment by olanti-p** [comment] 2022-02-06 13:08
> For me personally the look and feel of the graphical overmap that comes from the mod looks a lot better then the one provided by the game (true SDL). I have a feeling it fits better with the ASCII feeling of the game even when using tiles.

The "look" of the graphical overmap depends entirely on which tileset is in use.

<details>
  <summary>Examples</summary>

![image](https://user-images.githubusercontent.com/60584843/152681782-ea30e3ed-edd8-4f37-8bad-893ba23df5ab.png)
![image](https://user-images.githubusercontent.com/60584843/152681739-adcf3377-d394-4822-ba79-f01938619b4d.png)
![image](https://user-images.githubusercontent.com/60584843/152681822-0cf1a170-6eb1-49f7-991a-e92c3bec0080.png)

</details>
<details>
  <summary>Without tiles, for reference</summary>

![image](https://user-images.githubusercontent.com/60584843/152681673-f7db741b-6ca2-4bbd-9192-72e7c92df737.png)

</details>

> It this something we want supported though?

This will require extending some of SDL tile renderer functionality to no-tiles SDL renderer, and possibly also adding code support for changing font size on demand, which I personally see as bugprone and redundant.

Much better solution would be to implement "separate tileset for overmap" feature: this way, nothing will prevent someone from taking https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/font/map_font_LARWICK.png and turning it into an actual overmap tileset

**Comment by matshou** [comment] 2022-02-06 14:38
> Much better solution would be to implement "separate tileset for overmap" feature: this way, nothing will prevent someone from taking [font from mod](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0a8096cfd95d77ffb2a2d9fb9df81ff9ac7284f0/data/font/map_font_LARWICK.png) and turning it into an actual overmap tileset

I agree that this would be the way to go about this.

**Closed** 2022-02-10 09:53 UTC
