### ISSUE TITLE
 The "d:" type search is not working

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#3051] opened 2023-08-05 03:57 UTC
### Describe the bug

It seems be taking in consideration only the "basic" elements of the item's description, with stuff like compatible martial arts and special attacks showing nothing in the search at all, including the presented example for reach attacks.

### Steps To Reproduce

In the craft menu, d: search some propriety that will be in a text format that is not the default/basic used for the literal description of the items. I believe they all may be affected.

### Versions and configuration

Latest experimental + PR.

**Comment by Krwak** [comment] 2023-08-08 23:54
duplicate of #2903

**Comment by scarf005** [comment] 2023-08-08 23:59
hi @RodriguesCIA , thanks for the bug report. However as @Krwak pointed out, could you continue the dicussion in #2903, as it's been posted earlier? thank you.

**Closed by scarf005** 2023-08-08 23:59 UTC
Labels: bug
