### ISSUE TITLE
Equipping NPCs equipment crashes the game.

### ISSUE THREAD

**Issue by MisterWytt** [cataclysmbnteam/Cataclysm-BN#4353] opened 2024-03-14 22:48 UTC
### Describe the bug

I stripped down an NPC fully so I could equip them with some power armor. When I "E" them (Which you have them equip stuff on the floor) in their sort equipment menu, the game hard crashes. I tested it in a vanilla world and the same thing occurs.

### Steps To Reproduce

1. Recruit an NPC.
2. Strip them down.
3. Go into their Sort Armor menu, and have them equip any kind of armor on the floor
4. Watch the game crash.

### Screenshots

![Equipcrash](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/46728252/67a51f11-f2ab-473e-80cb-69b01f66c1ef)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4170 (22H2)
- Game Version: 8163b20 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by KheirFerrum** [comment] 2024-03-15 06:39
Related to #2743?

**Comment by scarf005** [comment] 2024-03-15 06:58
yeah, it's duplicate of #2743.

**Closed** 2024-03-15 07:20 UTC
Labels: bug
