### ISSUE TITLE
Cataclysm DDA and Cataclysm BN interfere with each other in GNU/Linux system

### ISSUE THREAD

**Issue by Brensom** [cataclysmbnteam/Cataclysm-BN#3497] opened 2023-10-24 08:54 UTC
### Describe the bug

If I have Cataclysm DDA installed, then when I try to install Cataclysm BN I get the error:
```
error: failed to commit transaction (conflicting files)
cataclysm-bn: /usr/bin/cataclysm exists in filesystem (owned by cataclysm-dda)
cataclysm-bn-tiles: /usr/bin/cataclysm-tiles exists in filesystem (owned by cataclysm-dda-tiles)
Errors occurred, no packages were upgraded.

```

### Steps To Reproduce

1.  Install Cataclysm DDA
2. Trying to install Cataclysm BN

### Versions and configuration

0.G (DDA)
0.4 (BN)

### Additional context

OS: Arch Linux x86_64
Kernel: 6.1.59-1-lts
local/cataclysm-dda 0.G-2
A post-apocalyptic roguelike.
local/cataclysm-dda-tiles 0.G-2
A graphical post-apocalyptic roguelike.

https://github.com/CleverRaven/Cataclysm-DDA/issues/68867

**Comment by paramendula** [comment] 2023-11-04 14:19
I guess only the author of this AUR > https://aur.archlinux.org/packages/cataclysm-bn may fix it.

By the way, try this awesome launcher: https://github.com/qrrk/Catapult
It allows you to keep your Cata(both DDA and BN) installations up to date and etc

**Comment by scarf005** [comment] 2023-11-04 14:23
i guess it's caused by both fork using default executable name `cataclysm` and `cataclysm-tiles`.

**Comment by Brensom** [comment] 2023-11-04 15:39
> By the way, try this awesome launcher: https://github.com/qrrk/Catapult It allows you to keep your Cata(both DDA and BN) installations up to date and etc
This project has been abandoned for a long time. And it only supports BN version 0.2, which was released back in March.

> i guess it's caused by both fork using default executable name `cataclysm` and `cataclysm-tiles`.
Why do games called cataclysm dark days ahead and cataclysm bright nights have the executable name `cataclysm`?
Why not just call them `cataclysm-dda` and `cataclysm-bn` from the beginning, so that it’s clear what you’re launching?
Even the original game has the executable name `cataclysm`.
Why not just make it clear what you're running? Why confuse people?

**Comment by olanti-p** [comment] 2023-11-04 20:56
> Why do games called cataclysm dark days ahead and cataclysm bright nights have the executable name cataclysm?

Both are forks of Cataclysm, and inherited Cataclysm build files in some form, and back then the executable was named `cataclysm`.

> Why not just call them cataclysm-dda and cataclysm-bn from the beginning, so that it’s clear what you’re launching?

When DDA was forked from Cataclysm, most likely nobody cared, because Cataclysm was dead and there would be no conflicts.

When BN was forked from DDA, there were much bigger problems to tackle like having the game build in the first place.

We're slowly fixing such DDA/BN installation conflicts as they're reported, like the ones with Android and macOS, but unfortunately due to the nature of how build systems are organized (there were 5 of them when BN forked off, and I don't even want to think of how many DDA has now) it's not as easy as switching a single option. Not to mention that all people familiar with build systems are either long gone from both projects, or have remained with DDA.

I was hoping to have Linux exe naming issue solved after I've sorted out the whole build system mess (#3113), but unfortunately I am but one person while the build targets are plenty.

> Why not just make it clear what you're running?

If you think this is intentional, you're welcome to help out with #3113. The task list includes:
- making Android gradle build work off the CMake project rather than its own custom Makefile (I've no idea how I'll be doing that, but it should be possible according to Google, so outside help is quite welcome)
- porting `dmgdist` target from Makefile to CMake
- vetting install locations for CMake install target on Linux, macOS and Windows
- porting translation utility targets from Makefile to CMake
- updating all documentation relevant to CMake builds for all targets

**Comment by RoyalFox2140** [comment] 2024-08-14 02:22
Should be fixed by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4989 please re-open if it's not

**Closed by RoyalFox2140** 2024-08-14 02:22 UTC
Labels: bug
