### ISSUE TITLE
Negative values when looking at this watch

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#4469] opened 2024-04-12 09:58 UTC
### Describe the bug

This watch has negative protection values, seems to be an overflow

### Steps To Reproduce

1. check the watch
2. see negative values

### Screenshots

![grafik](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/48abd17d-ea4b-4e57-8809-b812038c7077)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 9867e87 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies],
    Lootzones [Lootzone],
    No Filthy Clothing [no_filthy_clothing],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

[Wetteraukreis.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/14957186/Wetteraukreis.zip)

**Comment by chaosvolt** [comment] 2024-04-12 15:39
Duplicate of https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4300, it's a know visual issue for non-msvc windows builds. Last we tested it doesn't make you explode when hit at least...

**Closed by chaosvolt** 2024-04-12 15:39 UTC
Labels: bug
