### ISSUE TITLE
Joint Torsion Ratchet CBM

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3404] opened 2023-10-09 19:29 UTC
### Describe the bug

The Joint Torsion Ratchet CBM works as intended, when moving.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/fc156fb6-92d5-4072-a0dd-2fc0c29d446b)

However, when driving a bike, the joints still are moving, ergo it should be charging too.

### Steps To Reproduce

1. Get on a bike
2. Bike around
3. Watch CBM power not rise.
4. Be sad :sad

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 2bc98a8 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Necropolis Actually Findable [necro_find],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    Project: Pack Rat [Jake's_Squirrel_mod],
    More Bandits, Testing version [More_Bandits],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Morlock Village [morlock_village],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Really Dark Skies plus Arcana [realdarkskies_Arcana_patchmod],
    Really Dark Skies plus Cataclysm++ [realdarkskies_CATA_patchmod],
    Really Dark Skies plus Aftershock [realdarkskies_aftershock_patchmod],
    Really Dark Skies plus PKs Rebalancing [realdarkskies_PK_REBALANCE_patchmod],
    Really Dark Skies plus Secronom [realdarkskies_secronom_patchmod],
    Really Dark Skies plus C.R.I.T. [realdarkskies_CRIT_patchmod],
    Really Dark Skies plus Bio-Synth Robot Expansion [realdarkskies_gekkobots_patchmod],
    Really Dark Skies plus magiclysm [realdarkskies_magiclysm_patchmod],
    Really Dark Skies plus Morlock Village [realdarkskies_morlock_village_patchmod],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    DinoMod [DinoMod],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Really Dark Skies plus DinoMod [realdarkskies_Dino_patchmod],
    Valik's Machine Shop 1.1 [valikengines],
    CDDA Variety Pack [ks_variety_pack],
    Mug NPCs [mug_NPCs],
    NPC Recruitment Options [recruitment_options],
    Wandering Masters [wandering_masters],
    Nuclear Power Plant [NPP]
]

**Comment by Vollch** [comment] 2023-10-10 11:50
Duplicate of #2372

**Closed** 2023-10-10 12:04 UTC
Labels: bug
