### ISSUE TITLE
Empty container is gone if i press "r" to interact.

### ISSUE THREAD

**Issue by Ruby1621** [cataclysmbnteam/Cataclysm-BN#4057] opened 2024-01-05 17:04 UTC
### Describe the bug

Press "r" to transfer clean water (plastic bottle) to plastic bowl or else, a empty container is not appear.

### Steps To Reproduce

1. Get some bottle of water and bowl in shelter.
2. Press "r" to choose bowl and refill water.
3. A bottle isn't show up.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: v0.5.2 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    No Rail Stations [No_Rail_Stations],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by mythosmod** [comment] 2024-02-21 10:59
Unable to reproduce in latest version - able to select bowl to reload and then see bottles of water to reload from:

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/91185016/ce305e65-470a-4bd7-92fe-368f73f42b47)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/91185016/79620e26-698c-4c16-bf77-369bd2544b6c)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/91185016/581cf57e-4e41-4655-acf2-5942e9986d4e)

**Comment by joveeater** [comment] 2024-02-21 11:26
I think this was fixed by #4104.

**Closed by joveeater** 2024-02-21 11:26 UTC
Labels: bug
