### ISSUE TITLE
Spawning vehicles via scenarios and professions behaves strangely

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#594] opened 2021-06-13 01:07 UTC
# Describe the bug

When assigning a vehicle to spawn in a scenario, or at the profession level:
1. If a scenario is set to start the player off with a vehicle, it takes several turns after game start for it to appear.
2. Even if you start in a bare field, the vehicle seems to prefer spawning in a random nearby `om_terrain`.
2. It leaves a vehicle tracking marker where it spawned, but the marker stays there and seemingly can't be deleted, should you drive off.

# Steps To Reproduce

1. Start in The Last Delivery (spawned by scenario) or Ride of The Vaklyries (spawned by professions) scenarios.
2. Notice that you can't see your vehicle anywhere nearby, but the minimap should show a vehicle memory indicator close by.
3. Walk over in that direction, a vehicle will magic out of thin air after a few turns.
4. Drive or fly away, notice the vehicle tracking marker stays where your vehicle spawned.

# Expected behavior

1. Vehicles spawned by scenarios and professions to start off remembering they exist.
2. Vehicle starting in same om_terrain as the player so long as there is room in that area.
3. Vehicle tracking marker following the vehicle it's assigned to.

# Screenshots

Screenshot of area, with minimap highlighted. I'd previously drove the vehicle that spawned here up the road to the northeast.
![image](https://user-images.githubusercontent.com/11582235/121792320-09477b80-cbb9-11eb-9a03-cd33f4eae69a.png)

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 1943ad1 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Arcana and Magic Items [Arcana],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    Fewer Farms [Fewer_Farms],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins]
]
```

# Additional context

Side note, testing with The Last Delivery also has decent odds of a failure to find a starting location.

Discovered while tinkering with an idea for Tankmod: Revived.

**Comment by Coolthulhu** [comment] 2021-06-13 11:37
> Walk over in that direction, a vehicle will magic out of thin air after a few turns.

It's probably caused by using a second map to spawn the vehicle, then saving it there, but failing to update the map afterwards.
I'm currently experiencing hardware problems and can't fix things, but you could try fixing it by finding `game::start_game()`, then moving the vehicle spawn bits (near the bottom) above `update_map()` call.

As for tracking, in `game::place_vehicle_nearby`, in `if( veh )`, add a line: `veh->tracking_on = true;`.

**Comment by chaosvolt** [comment] 2021-06-13 21:15
> It's probably caused by using a second map to spawn the vehicle, then saving it there, but failing to update the map afterwards.
I'm currently experiencing hardware problems and can't fix things, but you could try fixing it by finding game::start_game(), then moving the vehicle spawn bits (near the bottom) above update_map() call.

I'll see if I can tinker with it in a bit, just got home.

> As for tracking, in game::place_vehicle_nearby, in if( veh ), add a line: veh->tracking_on = true;.

Will that cause the existing tracker marker to properly follow the vehicle? Since that's the problem, it's placing what looks like a normal vehicle tracking marker, except it stays in the location the vehicle spawned in.

**Comment by Coolthulhu** [comment] 2021-06-14 03:42
> Will that cause the existing tracker marker to properly follow the vehicle?

I'm pretty sure it should. There are two components to tracking: overmap marker and moving it. Moving is done in `map`, in functions that move the vehicle on local map, but only to vehicles that have tracking on.
If you want to make sure: try starting a new character with vehicle and remembering the vehicle before driving off. If it causes the marker to move, it'll work with tracking on. If it creates a separate marker, it may work or may not work.

**Comment by chaosvolt** [comment] 2021-06-14 04:33
Ah, okay. I'll mess with testing later on or tomorrow, if I get time. ^^"

**Comment by chaosvolt** [comment] 2021-06-15 18:43
Testing the first recommended change, seems to work:
![image](https://user-images.githubusercontent.com/11582235/122106483-9704b000-cddf-11eb-81a5-23410d55c302.png)

Pictured is helicopter spawned nearby the very instant I spawn in. Next I'll test messing around with the tracker.

**Closed** 2021-06-21 17:35 UTC
