### ISSUE TITLE
"Item rag was loaded with charges, but can not have any!"

### ISSUE THREAD

**Issue by falcorr** [cataclysmbnteam/Cataclysm-BN#2363] opened 2023-02-21 08:04 UTC
### Describe the bug

Error screen, can continue through it.

### Steps To Reproduce

Loading a savegame.

### Screenshots

![catabntempbug](https://user-images.githubusercontent.com/65019252/220283994-554f7d01-ac50-4ea9-b775-44f0bb1ba172.png)

### Versions and configuration

BN 0.2, line 2331

### Additional context

I'm loading into a place surrounded by many items in adjacent squares, including a bunch of rags. I don't think there are any rags in the inventory.

I'm able to continue into the game (and play at length) without apparent issue.

**Comment by olanti-p** [comment] 2023-03-13 14:39
This looks like either some mod modified rags to have charges, then was either removed or updated to no longer do that, or the rags were erroneously spawned with charges at some point through the game, and it only came up after a save/load cycle.

Were you using mods? Could you post the save from back then, if you still have it?

> I'm able to continue into the game (and play at length) without apparent issue.

Yes, this error is more of a warning. The game also fixes the item at that moment, so if you've saved since then and the error did not repeat than it most likely fixed itself.

**Comment by olanti-p** [comment] 2023-09-23 00:43
Closing for now, can't reproduce. Must've been some one-off thing.

**Closed by olanti-p** 2023-09-23 00:43 UTC
Labels: bug
