### ISSUE TITLE
Long grass cannot be driven through, behaves like a concrete wall

### ISSUE THREAD

**Issue by Arkaile** [cataclysmbnteam/Cataclysm-BN#2891] opened 2023-05-26 22:16 UTC
### Describe the bug

When driving a vehicle onto a tile of long grass, it behaves as though it is a concrete wall. I tried installing the Shrub It Off mod and found that it made no difference.

### Steps To Reproduce

Make a character and drive any vehicle into long grass.

### Screenshots

Here I spawned in a car and crashed it into some long grass. The vehicle destroyed one tile of it and what was left in its place is a pit.

![long grass is hard](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/73376008/1ea24c8a-21ff-4df4-b94e-dab8c5087502)

### Versions and configuration

OS: Windows 10 x64
Game version: 5b815d9
Graphics Version: Tiles
In-game Language: English
Mods loaded: Bright Nights, Disable NPC Needs, Simplified Nutrition, No Rail Stations, Elevated Bridges

**Comment by chaosvolt** [comment] 2023-05-27 04:42
...huh. Somehow caused by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2842 I'm assuming?

**Comment by chaosvolt** [comment] 2023-05-27 04:55
Ahah, looks like this can be fixed by adding the `NOCOLLIDE` flag.

**Comment by KoRv117** [comment] 2023-05-28 03:37
Just a heads up I think the same thing happens with bushes too. I know you normally collide with bushes but its also causing the same massive crash, a small pit in the ground, and likely some serious damage to the vehicle.

![Bush Smash Picture](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/56089860/702bbb06-7279-475c-8095-105f8bfcbe73)

![Bush Smash Log](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/56089860/4a982b0a-2c61-4f4c-b243-84f6eb3747bf)

**Closed** 2023-05-29 06:21 UTC
Labels: bug
