### ISSUE TITLE
Heat info on the sidebar is stuck at "Freezing"

### ISSUE THREAD

**Issue by blot-runner** [cataclysmbnteam/Cataclysm-BN#5591] opened 2024-10-20 12:40 UTC
### Describe the bug

Heat info on the sidebar displays "Freezing" state regardless of the actual temperature. From what I could see, the issue is limited to the sidebar (i.e. character screen and the tileset moodlet show id the character is hot and, high heat debuffs are applied).

### Steps To Reproduce

1. Create a new world, no mods, default settings.
2. Create a default (shelter start) character.
3. Observe "Freezing" heat level on the sidebar.
4. Find (or debug in) clothes and blankets and wear them, the more the better.
5. Wait till the log starts warning you're in pain.
7. View player info (default key: @) to confirm the character is warm/hot and has heat debuffs.
8. Observe the heat level on the sidebar still insisting the character is freezing (see screenshot).
![image](https://github.com/user-attachments/assets/669d5caa-59e8-4b94-987f-8f30c9cd43e1)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: 88c3a84 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]

**Comment by RoyalFox2140** [comment] 2024-10-21 11:47
Yes we know, it's caused by the PR I'm linking down below. I made the mistake of reviewing that PR in the dev channels on Discord but forgetting to report the bugs on the PR directly so it got merged with bugs.

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5557

**Closed** 2024-10-21 20:03 UTC
Labels: bug, confirmed, src
