### ISSUE TITLE
Autoattacking on stairs can reach enemies below you

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#2386] opened 2023-03-03 20:15 UTC
### Describe the bug

When standing on stairs and there are enemies in the Z-Level below you (were the stairs lead), you can spam the auto attack button. You will attack them, but they won't attack you, making it an easy way to get rid of the zombies.

### Steps To Reproduce

1. Find a house with a cellar, which includes zombies
2. Stand on the stair tile, when enemies are below you
3. press the "auto attack" button and hit enemies, while you are immune.

### Screenshots

![grafik](https://user-images.githubusercontent.com/33199510/222819106-9988d4ef-423d-456c-b119-ae3a68b4a6be.png)
![grafik](https://user-images.githubusercontent.com/33199510/222819280-f0683ee0-38aa-4d3c-8f95-820cc60f0911.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 4b6fa84 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Lifting Reqs [disable_lifting],
    meins [meins],
    Generic Guns by me! [generic_guns_impr],
    Zero Gunmod Volume [ZeroGunmodVolume]
]

**Comment by chaosvolt** [comment] 2023-03-03 21:36
Being able to clear the stairs by attacking instead of being permanently softlocked by some zeds on the other side seems intended behavior, them not being able to return the favor and fight back however seems to be unintended.

**Comment by scarf005** [comment] 2023-04-19 14:53
https://user-images.githubusercontent.com/54838975/233114753-17fc7b11-b064-4feb-b37b-de5892bd32df.mp4
also found out that it's not just confined to stairs, you can attack any enemy below you if you have vision (e.g: clairvoyance).

**Comment by AniDemi** [comment] 2023-05-05 11:17
From a quick test myself, and unless I did something wrong, the behaviour is now.
With experimental vision: They can attack, I can attack
![image](https://user-images.githubusercontent.com/60388907/236443950-cf04d032-8df1-4d7f-8529-ceb0fc4f5210.png)

Without experiemental vision: They can attack, I can't attack
![image](https://user-images.githubusercontent.com/60388907/236443655-4eafc92b-0d61-4d46-bd78-98ce58cad94e.png)

**Comment by Coolthulhu** [comment] 2023-06-15 01:14
Closing as "not planned": player can still autoattack, enemies can now attack up/down stairs as well. However this is dependent on stairs being aligned, which isn't always the case.

The clairvoyance bug is still not fixed.

**Closed by Coolthulhu** 2023-06-15 01:14 UTC
Labels: bug
