### ISSUE TITLE
Crashing when browsing / searching in crafting UI

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3399] opened 2023-10-09 06:05 UTC
### Describe the bug

When browsing or searching the crafting UI, game closes/crashes without a log when hitting specific items.

Last working build: Cataclysm-BN experimental build 2023-10-07-1508

### Steps To Reproduce

1. Open crafting UI
2. Search for `d:Project: Pack Rat` or `survivor's .223 ammo belt` or `survivor's 7.62x39 ammo belt`
3. Game closes / crashes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 39e4273 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    BL9-140%-monster-resilience-version [BL9_140monres],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    ...and a gazillion more mods...
]

### Additional context

See more details in See more details on discord https://discord.com/channels/830879262763909202/830916451517857894/1160506922592637039 .

**Comment by chaosvolt** [comment] 2023-10-09 17:33
If I recall, the Cata++ ammo belts act like regular magazines instead due to being non-disintegrating: https://github.com/Noctifer-de-Mortem/nocts_cata_mod/blob/master/nocts_cata_mod_BN/Weapons/c_magazines.json#L149

Can you repeat this test with one of the standard survivor mags in Cata++ to confirm it's not something wrong with Cata++ mags in general? Like `survivor's .223 magazine` for example. For what I can see, the main differences are:
1. They're set to not count as rigid.
2. They have armor data since regular ammo belts can be worn too.

The regular ammo belt has mostly the same data except the Cata++ version has added encumbrance: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/items/classes/magazine.json#L14

Regular ammo belts aren't directly craftable since you craft the links instead, so I'm not sure how to weed out whether vanilla ammo belts do this too or not. Doing a `d:` search in a pile of items in AIM or the `g` menu might work for it?

**Comment by OrenAudeles** [comment] 2023-10-09 17:59
> Can you repeat this test with one of the standard survivor mags in Cata++ to confirm it's not something wrong with Cata++ mags in general? Like `survivor's .223 magazine` for example. For what I can see, the main differences are:

In my testing to see what causes the issue I changed the `if( capacity < 0 )` condition to `<= 0` so it would emit debug messages
```cpp
if( capacity < 0 ) {
    debugmsg( "Non-rigid item (%s) without storage capacity.", tname() );
} else {
    // Cast up to 64 to prevent overflow. Dividing before would prevent this but lose data.
    encumber += static_cast<int64_t>( entry.max_encumber - entry.encumber ) * contents_volume.value() /
                capacity;
}
```
In the debug log when searching `d:Project: Pack Rat` it only emitted on the ammo belts listed in the previous comment.
Relevant snip from debug.log
```text
06:11:04.185 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's .223 ammo belt) without storage capacity.
06:11:13.676 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's .223 ammo belt) without storage capacity.
06:11:16.975 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's .308 ammo belt) without storage capacity.
06:11:23.662 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] (error message will follow backtrace)
[backtrace omitted]
06:11:25.125 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's 7.62x39 ammo belt) without storage capacity.

06:11:25.136 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's 7.62x39 ammo belt) without storage capacity.
06:11:25.145 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's 7.62x54 ammo belt) without storage capacity.
06:11:25.902 ERROR DEBUGMSG : src/item.cpp:5891 [int item::get_encumber_when_containing(const Character&, const volume&, const bodypart_id&) const] Non-rigid item (<color_c_light_green>|| </color>survivor's 7.62x54 ammo belt) without storage capacity.
```

**Comment by chaosvolt** [comment] 2023-10-09 18:01
`Non-rigid item (<color_c_light_green>|| </color>survivor's 7.62x39 ammo belt) without storage capacity.`

Ah, that's...weird. Shouldn't stuff like vanilla ammo belts also trigger that then?

In any case, easy fix I guess is to remove rigid from the ammo belts in Cata++ since they're noted to be non-disintegrating, plus on top of that they already have a decent base volume defined.

**Comment by OrenAudeles** [comment] 2023-10-09 18:02
It's pretty weird, yeah

**Comment by chaosvolt** [comment] 2023-10-09 19:05
Should now be fixed by https://github.com/Noctifer-de-Mortem/nocts_cata_mod/pull/560 but let me know. Plus, sounds like there's some underlying code weirdness that's the root cause of this, and may cause trouble in the future.

**Comment by OrenAudeles** [comment] 2023-10-09 20:30
> Plus, sounds like there's some underlying code weirdness that's the root cause of this, and may cause trouble in the future.

Likely, and should have been caught earlier. The issue cropped up after the bodypart PR #2776 was merged. Prior to that the code that produces the crash didn't exist, and looking at the PR's changes to item.cpp L5894-5895 you see that the clang analyzer warns for a potential divide by zero.

**Closed** 2023-10-14 04:51 UTC
Labels: bug, crash
