### ISSUE TITLE
Unable to generate a valid location

### ISSUE THREAD

**Issue by Trokinos** [cataclysmbnteam/Cataclysm-BN#148] opened 2020-10-27 14:41 UTC
Using cataclysmbn-728-win64-tiles

# Describe the bug
After playing a character and that character got killed, i experienced a couple of time a bug , starting a New Game with the same character preset will lead to a message "Unable to generate a valid location" 

# Steps To Reproduce
Started the game
mods used only to simplify nutrition , speedydex, no filthy clothes and stats through skills, nothing else that could add locations or worldgen changes.
Created a "Military Recruit" character with the scenario "Overrun" .
Changed the "random starting location" to the military warehouse (Overrun has only 1 possible location anyways)
Played that character, exited the military warehouse and got killed while trying to flee with army zombies shooting at me to slow me down and the horde finally overwhelming me.
Quit the game
Launched the game
New Game -> Preset Character -> Last Character
wait until load then start the game,

NOTE : it only happened 3 times in a row on my attempts to reproduce that oddity, but since then it has worked normally a dozen of time without error, so i have no idea what caused the problem.

**Comment by Coolthulhu** [comment] 2020-10-31 12:53
Sometimes certain "mandatory" locations just fail to generate. This is an old problem that is not easy to fix.

**Comment by Drugitechnik** [comment] 2022-09-20 17:29
possible duplicate of #36 
possibly fixed in #1369

**Closed** 2022-09-24 13:43 UTC
Labels: bug, invalid
